# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29fb509bc8d4f14a7ac003ebf8e73a01e585f078b378cea53259d2e722ca9ed935bc56aa75f046b659a9b3296811ce10f3a1a1f496ba39e637ae456ca107f4fb

test:
  secret_key_base: 8636f426ac79a42944e06f7708e778032fa25d47de70eefcfa02d4c7f06636994aa36390ba0ec59702371aa1da756390dfd1b5af3b9b43b29e4bf21ba45bf7e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
